services:
  - type: web
    name: scrapsutra-v1
    env: python
    buildCommand: pip install -r requirements.txt && python init_db.py
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_DEBUG
        value: False
      - key: PYTHON_VERSION
        value: 3.10.11
      - key: GEMINI_API_KEY
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: FIREBASE_API_KEY
        sync: false
      - key: FIREBASE_AUTH_DOMAIN
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_STORAGE_BUCKET
        sync: false
      - key: FIREBASE_MESSAGING_SENDER_ID
        sync: false
      - key: FIREBASE_APP_ID
        sync: false
